### ISSUE TITLE
angular-route.js not included in index.html

### ISSUE THREAD

**Issue by osirisguitar** [Iteam1337/generator-mrwhite#5]
Angular.js 1.2.1 was automatically added, needs angular-route.js explicitly included in the index.html file.

**Comment by osirisguitar** [comment]
Or should that be ui-router?

**Comment by irony** [comment]
It should be ui-router and the template should instead of adding a .when('/url') row should instead add a     .state('name', {url: '/url', templateUrl: 'partial/name/template.html'})
